name: Task
description: Any task, chore, or work item that needs to be done
title: "🔧 [Task]: "
labels: ["task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Tasks can be technical work, administrative items, documentation, or any other work that needs tracking. Use this template for work that doesn't fit the Story, Bug, or Enhancement categories.

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What kind of task is this?
      options:
        - Technical - Refactoring, technical debt, performance
        - Infrastructure - DevOps, deployment, configuration
        - Documentation - Write or update docs
        - Testing - Add or improve tests
        - Security - Security improvements or audits
        - Dependencies - Update or maintain dependencies
        - Administrative - Planning, organization, process
        - Research - Investigation or exploration
        - Other - Something else
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What's the current state and why does this need attention?
      placeholder: |
        Example: We need to update our deployment documentation to reflect the new CloudFlare tunnel configuration. The current docs still reference the old setup and are confusing new team members.
    validations:
      required: true

  - type: textarea
    id: desired-outcome
    attributes:
      label: Desired Outcome
      description: What will improve after this work is complete?
      placeholder: |
        Example: Documentation accurately reflects current infrastructure, making it easy for new team members to understand and deploy services.
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Approach
      description: How should this be done? (Optional - can be figured out during implementation)
      placeholder: |
        - Step 1: Review current tunnel configuration
        - Step 2: Update architecture.md
        - Step 3: Update deployment runbooks
        - Step 4: Test instructions with a new team member
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this is complete?
      placeholder: |
        - [ ] Criterion 1 is met
        - [ ] Criterion 2 is met
        - [ ] Changes are documented
        - [ ] Work is verified/tested
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this work?
      options:
        - Critical - Blocking or urgent
        - High - Important, should do soon
        - Medium - Moderate importance
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact & Scope
      description: What's affected by this work?
      placeholder: |
        - Affected areas: [files, systems, people]
        - Dependencies: [what needs to exist first]
        - Breaking changes: [yes/no, details]
        - Estimated effort: [hours/days]
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information, considerations, or context
      placeholder: |
        - Risks or concerns
        - Dependencies or blockers
        - Resources or references
        - Related issues or PRs
    validations:
      required: false

  - type: textarea
    id: parent-task
    attributes:
      label: Parent Task/Epic
      description: Is this a sub-task of another issue? Link to the parent task or epic.
      placeholder: |
        Part of #123
        
        Or for Epic: Part of Epic #15
    validations:
      required: false

